<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Cratis.Architecture.CodeAnalysis.Specs</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);CS1591;SA1600;SA1601;MA0136;MA0006;MA0004;CA2007;CA1859</NoWarn>
    <RunAnalyzers>false</RunAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="System.Text.Json" />
    <PackageReference Remove="Microsoft.SourceLink.GitHub" />
    <PackageReference Remove="Cratis.Fundamentals" />
    <PackageReference Remove="Cratis.Specifications.XUnit" />
    <ProjectReference Include="../CodeAnalysis/Cratis.Architecture.CodeAnalysis.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
